import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import PhoneIphoneIcon from '@mui/icons-material/PhoneIphone';
import EmailIcon from '@mui/icons-material/Email';
import {Box, Grid, Paper, Typography} from "@mui/material";
import DevIcon from "devicon-react-svg"
import Link from "next/link";



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>남승현 이력서</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">My Resume</a>
        </h1>

        <Box className={styles.box}>
            <h2>5년차 Back-end 개발자</h2>
        </Box>
        <Box className={styles.box}>
          <PhoneIphoneIcon/><code className={styles.code}> 010-2628-2096 </code>
        </Box>
        <Box className={styles.box}>
          <EmailIcon/><code className={styles.code}> cakor2096@naver.com </code>
        </Box>


        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Skills &rarr;</h2>
            <Grid container spacing={2}>
              <Grid item xs={2}>
                <DevIcon icon="java" style={{width:"30px"}}/>
              </Grid>
              <Grid item xs={2}>
                <DevIcon icon="python" style={{width:"30px"}}/>
              </Grid>
              <Grid item xs={2}>
                <DevIcon icon="django" style={{width:"30px"}}/>
              </Grid>
              <Grid item xs={2}>
                <DevIcon icon="javascript" style={{width:"30px"}}/>
              </Grid>
              <Grid item xs={2}>
                <DevIcon icon="react" style={{width:"30px"}}/>
              </Grid>
              <Grid item xs={2}>
                <DevIcon icon="nodejs" style={{width:"30px"}}/>
              </Grid>
              <Grid item xs={2}>
                <DevIcon icon="mysql" style={{width:"30px"}}/>
              </Grid>
              <Grid item xs={2}>
                <DevIcon icon="mongodb" style={{width:"30px"}}/>
              </Grid>
              <Grid item xs={2}>
                <DevIcon icon="git" style={{width:"30px"}}/>
              </Grid>
              <Grid item xs={2}>
                <DevIcon icon="docker" style={{width:"30px"}}/>
              </Grid>
              <Grid item xs={2}>
                <DevIcon icon="aws" style={{width:"30px"}}/>
              </Grid>
              <Grid item xs={2}>
                <DevIcon icon="nginx" style={{width:"30px"}}/>
              </Grid>
            </Grid>
          </a>

          <Link href="/WorkExperience" className={styles.card}>
            <h2>Work Experience &rarr;</h2>
            <p style={{margin:15}}>Amass Senior Engineer</p>
            <p style={{margin:15}}>5년차 Back-end 개발자</p>
          </Link>

          {/*<a*/}
          {/*  href="https://github.com/vercel/next.js/tree/canary/examples"*/}
          {/*  className={styles.card}*/}
          {/*>*/}
          {/*  <h2>Examples &rarr;</h2>*/}
          {/*  <p>Discover and deploy boilerplate example Next.js projects.</p>*/}
          {/*</a>*/}

          {/*<a*/}
          {/*  href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
          {/*  className={styles.card}*/}
          {/*>*/}
          {/*  <h2>Deploy &rarr;</h2>*/}
          {/*  <p>*/}
          {/*    Instantly deploy your Next.js site to a public URL with Vercel.*/}
          {/*  </p>*/}
          {/*</a>*/}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
